name: btg_funds_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  bloc: 
  connectivity_plus:
  dartz: 
  equatable: 
  flutter:
    sdk: flutter
  flutter_bloc: 
  freezed_annotation: 
  get_it: 
  go_router: 
  hive_flutter: 
  injectable: 
  internet_connection_checker_plus:
  intl: 
  json_annotation: 
  logger: 
  uuid: 

dev_dependencies:
  bloc_test: 
  build_runner: 
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: 
  injectable_generator: 
  json_serializable: 
  mocktail: 
  very_good_analysis: 

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#0051A8"
    theme_color: "#0051A8"
  image_path: "assets/icon/app_icon.png"
  background_color_android: "#0051A8"
  adaptive_icon_background: "#0051A8"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/data/
    - assets/icon/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
